#config_version=5
mode:
  start_events: start_warp_ramp_multiball_mode_request
  stop_events: stop_warp_ramp_multiball_mode_request
  priority: 1000

event_player:
  warp_ramp_mb_jackpot_shot_jackpotpending_hit: warp_ramp_mb_award_jackpot
  balldevice_bd_plunger_ejecting_ball: plaid_multiball_raise_orbit_post|1000ms
  multiball_plaid_multiball_started: plaid_multiball_raise_orbit_post
  multiball_plaid_multiball_ended: warp_ramp_multiball_complete|50ms
  stop_warp_ramp_multiball_request: award_next_schwartz_gem

show_player:
  multiball_plaid_multiball_started:
    ball_saver_timer_show:
      loops: 0
      speed: 1    
  multiball_plaid_multiball_ended:
    ball_saver_timer_show:
      action: stop

coil_player:
  multiball_plaid_multiball_ended:
    c_orbit_post:
      action: disable
  balldevice_bd_plunger_ejecting_ball:
    c_orbit_post:
      action: disable
  plaid_multiball_raise_orbit_post:
    c_orbit_post:
       action: enable
       hold_power: 0.5

variable_player:
  warp_ramp_mb_award_jackpot:
    score: 500000 * current_player.game_scoring_multiplier

shots:
  warp_ramp_mb_jackpot_shot:
    hit_events: warp_ramp_full_jackpot_hit
    profile: warp_ramp_mb_jackpot_shot_profile
    reset_events: warp_ramp_mb_award_jackpot

sequence_shots:
  warp_ramp_full_jackpot:
    switch_sequence: s_ramp_entry, s_ramp_exit
    sequence_timeout: 3s

shot_profiles:
  warp_ramp_mb_jackpot_shot_profile:
    states:
      - name: jackpotpending
        loops: -1
        show: warp_ramp_mb_jackpot_pending
