#config_version=5
mode:
  start_events: ball_starting
  priority: 700

event_player:
  lonestar_save_my_daughter_video_ended: sbone_vespa_qualifier_fanfare_ended

slide_player:
  sbone_ball_one_locked:
    sbone_vespa_ball_one_locked_video:
      target: lcd
  you_forgot_to_get_married_video_ended:
    sbone_vespa_ball_one_locked_video:
      target: lcd
      action: remove
  sbone_ball_two_locked:
    sbone_vespa_ball_two_locked_video:
      target: lcd
  mercedes_taking_off_video_ended:
    sbone_vespa_ball_two_locked_video:
      target: lcd
      action: remove
  play_sbone_vespa_qualifier_complete_fanfare:
    sbone_vespa_ball_three_locked_video:
      target: lcd
  lonestar_save_my_daughter_video_ended:
    sbone_vespa_ball_three_locked_video:
      target: lcd
      action: remove
  player_sbone_mb_lock_locked_balls{value>0}:
    sbone_balls_locked_slide:
      target: dmd
      expire: 1
  multiball_sbone_multiball_started:
    sbone_multiball_started_slide:
      target: dmd
    sbone_multiball_tractorbeam_start_slide:
      target: lcd
  multiball_sbone_multiball_ended:
    sbone_multiball_started_slide:
      target: dmd
      action: remove
  video_tractor_beam_start_stopped:
    sbone_multiball_tractorbeam_start_slide:
      target: lcd
      action: remove
  sbone_multiball_award_100k_shot:
    sbone_mb_100k_award_slide:
      target: dmd
      expire: 1
  sbone_multiball_award_jackpot_shot:
    sbone_mb_jackpot_award_slide:
      target: dmd
      expire: 1

queue_relay_player:
  initiate_sbone_vespa_qualifier_complete_fanfare:
    post: play_sbone_vespa_qualifier_complete_fanfare
    wait_for: sbone_vespa_qualifier_fanfare_ended

sound_player:
  sbone_ball_one_locked:
    ball_one_locked_1:
      action: play
  sbone_ball_two_locked:
    ball_two_locked_1:
      action: play
  sbone_ball_three_locked:
    ball_three_locked_1:
      action: play
  multiball_sbone_multiball_started:
    multiball_callout_sound_pool:
      action: play
  sbone_multiball_award_100k_shot:
    target_hit_1:
      action: play
  sbone_multiball_award_jackpot_shot:
    jackpot_callout_sound_pool:
      action: play

slides:
  sbone_vespa_ball_one_locked_video:
    widgets:
      - type: video
        video: you_forgot_to_get_married
        width: 1280
        height: 720
  sbone_vespa_ball_two_locked_video:
    widgets:
      - type: video
        video: mercedes_taking_off
        width: 1280
        height: 720
  sbone_vespa_ball_three_locked_video:
    widgets:
      - type: video
        video: lonestar_save_my_daughter
        width: 1280
        height: 720
  sbone_balls_locked_slide:
    widgets:
      - type: text
        text: BALL (value) LOCKED
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 2
        x: center
        color: ffffff
      - type: text
        text: 100,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 2
        x: center
        color: ffffff
      - type: rectangle
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
        width: 128
        height: 32
        color: 000050
  sbone_multiball_started_slide:
    widgets:
      - type: text
        text: SBONE MB
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
  sbone_multiball_tractorbeam_start_slide:
    widgets:
      - type: video
        video: tractor_beam_start
        width: 1280
        height: 720
  sbone_mb_100k_award_slide:
    widgets:
      - type: text
        text: 100,000
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
  sbone_mb_jackpot_award_slide:
    widgets:
      - type: text
        text: JACKPOT
        style: dmd_xl
        anchor_y: top
        anchor_x: center
        y: top
        x: center
        color: ff00ff
      - type: text
        text: 1,000,000
        style: dmd_xl
        anchor_y: bottom
        anchor_x: center
        y: bottom
        x: center
        color: ffffff

    
