#config_version=5
mode:
  start_events: ball_starting
  priority: 700

event_player:
  lonestar_save_my_daughter_video_ended: sbone_vespa_qualifier_fanfare_ended
  you_forgot_to_get_married_video_ended: sbone_vespa_qualifier_ball_locked_fanfare_ended
  play_sbone_vespa_qualifier_ball_one_locked_fanfare: play_sbone_ball_locked_1_sound, play_sbone_vespa_qualifier_ball_one_locked_video|1000ms
  play_sbone_vespa_qualifier_complete_fanfare: play_sbone_ball_locked_2_sound, play_sbone_vespa_qualifier_ball_two_locked_video|1000ms

widget_player:
  timer_vespa_tractorbeam_timer_tick:
    vespa_mb_timer_time_remaining:
      slide: base_game_lcd_slide
  sbone_vespa_multiball_complete:
    vespa_mb_timer_time_remaining:
      slide: base_game_lcd_slide
      action: remove
  timer_vespa_tractorbeam_timer_complete:
    vespa_mb_timer_time_remaining:
      slide: base_game_lcd_slide
      action: remove

slide_player:
  logicblock_jamming_targets_hit_counter_hit{count==2}:
    sbone_vespa_mb_jamming_magnetic_beam_video:
      target: lcd
  theyve_got_her_in_the_magnetic_beam_video_ended:
    sbone_vespa_mb_jamming_magnetic_beam_video:
      target: lcd
      action: remove
  logicblock_jamming_targets_hit_counter_hit{count==4}:
    sbone_vespa_mb_jamming_down_scope_video:
      target: lcd
  down_scope_video_ended:
    sbone_vespa_mb_jamming_down_scope_video:
      target: lcd
      action: remove
  logicblock_jamming_targets_hit_counter_hit{count==6}:
    sbone_vespa_mb_jamming_periscope_view_video:
      target: lcd
  periscope_view_one_video_ended:
    sbone_vespa_mb_jamming_periscope_view_video:
      target: lcd
      action: remove
  saving_vespa_succeeded:
    sbone_vespa_mb_jamming_jamming_radar_video:
      target: lcd
  jam_hitting_radar_video_stopped:
    sbone_vespa_mb_jamming_jamming_radar_video:
      target: lcd
      action: remove  
  timer_vespa_tractorbeam_timer_tick{ticks_remaining==45}:
    sbone_vespa_tractorbeam_timer_seconds_left_dmd:
      target: dmd
      expire: 1
  timer_vespa_tractorbeam_timer_tick{ticks_remaining==30}:
    sbone_vespa_tractorbeam_timer_seconds_left_dmd:
      target: dmd
      expire: 1
  timer_vespa_tractorbeam_timer_tick{ticks_remaining==15}:
    sbone_vespa_tractorbeam_timer_seconds_left_dmd:
      target: dmd
      expire: 1
  counter_jamming_targets_hit_counter_hit:
    sbone_vespa_mb_jamming_hits_left:
      target: dmd
      expire: 1
  play_radar_sweep_display_1:
    radar_sweep_one_video:
      target: lcd
  radar_blip_video_ended:
    radar_sweep_one_video:
      target: lcd
      action: remove    
  play_radar_sweep_display_2:
    radar_sweep_two_video:
      target: lcd
  the_sweeps_video_ended:
    radar_sweep_two_video:
      target: lcd
      action: remove    
  play_sbone_vespa_qualifier_ball_one_locked_video:
    sbone_vespa_ball_one_locked_video:
      target: lcd
  you_forgot_to_get_married_video_ended:
    sbone_vespa_ball_one_locked_video:
      target: lcd
      action: remove
  play_sbone_vespa_qualifier_ball_two_locked_video:
    sbone_vespa_ball_two_locked_video:
      target: lcd
  lonestar_save_my_daughter_video_ended:
    sbone_vespa_ball_two_locked_video:
      target: lcd
      action: remove
  player_sbone_mb_lock_locked_balls{value>0}:
    sbone_balls_locked_slide:
      target: dmd
      expire: 1
  multiball_sbone_vespa_2ball_multiball_started:
    sbone_vespa_multiball_started_slide:
      target: dmd
      expire: 1
    sbone_multiball_tractorbeam_start_slide:
      target: lcd
  video_tractor_beam_start_stopped:
    sbone_multiball_tractorbeam_start_slide:
      target: lcd
      action: remove
  sbone_multiball_award_100k_shot:
    sbone_mb_100k_award_slide:
      target: dmd
      expire: 1
  sbone_multiball_award_jackpot_shot:
    sbone_mb_jackpot_award_slide:
      target: dmd
      expire: 1

queue_relay_player:
  initiate_sbone_vespa_qualifier_complete_fanfare:
    post: play_sbone_vespa_qualifier_complete_fanfare
    wait_for: sbone_vespa_qualifier_fanfare_ended

sound_player:
  play_sbone_ball_locked_1_sound:
    ball_one_locked_1:
      action: play
  play_sbone_ball_locked_2_sound:
    ball_two_locked_1:
      action: play
  multiball_sbone_vespa_2ball_multiball_started:
    multiball_callout_sound_pool:
      action: play
  sbone_multiball_award_100k_shot:
    target_hit_1:
      action: play
  sbone_multiball_award_jackpot_shot:
    jackpot_callout_sound_pool:
      action: play

slides:
  sbone_vespa_mb_jamming_jamming_radar_video:
    widgets:
      - type: video
        video: jam_hitting_radar
        width: 1280
        height: 720
  sbone_vespa_mb_jamming_periscope_view_video:
    widgets:
      - type: video
        video: periscope_view_one
        width: 1280
        height: 720
  sbone_vespa_mb_jamming_magnetic_beam_video:
    widgets:
      - type: video
        video: theyve_got_her_in_the_magnetic_beam
        width: 1280
        height: 720
  sbone_vespa_mb_jamming_down_scope_video:
    widgets:
      - type: video
        video: down_periscope
        width: 1280
        height: 720
  sbone_vespa_tractorbeam_timer_seconds_left_dmd:
    widgets:
      - type: text
        text: (ticks_remaining)
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 1
        x: center
        color: ff5555
      - type: text
        text: SECONDS LEFT
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 1
        x: center
        color: ffffff
  sbone_vespa_mb_jamming_hits_left:
    widgets:
      - type: text
        text: (remaining) HITS
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 1
        x: center
        color: ff5555
      - type: text
        text: TO JAM RADAR
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 1
        x: center
        color: ff5555
  radar_sweep_one_video:
    widgets:
      - type: video
        video: radar_blip
        width: 1280
        height: 720
  radar_sweep_two_video:
    widgets:
      - type: video
        video: the_sweeps
        width: 1280
        height: 720
  sbone_vespa_ball_one_locked_video:
    widgets:
      - type: video
        video: you_forgot_to_get_married
        width: 1280
        height: 720
  sbone_vespa_ball_two_locked_video:
    widgets:
      - type: video
        video: lonestar_save_my_daughter
        width: 1280
        height: 720
  sbone_balls_locked_slide:
    widgets:
      - type: text
        text: BALL (value) LOCKED
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top - 2
        x: center
        color: ffffff
      - type: text
        text: 100,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 2
        x: center
        color: ffffff
      - type: rectangle
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0
        width: 128
        height: 32
        color: 000050
  sbone_vespa_multiball_started_slide:
    widgets:
      - type: text
        text: SAVE VESPA!
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
  sbone_multiball_tractorbeam_start_slide:
    widgets:
      - type: video
        video: tractor_beam_start
        width: 1280
        height: 720
  sbone_mb_100k_award_slide:
    widgets:
      - type: text
        text: 100,000
        style: dmd_xl
        anchor_y: center
        anchor_x: center
        y: center
        x: center
        color: ffffff
  sbone_mb_jackpot_award_slide:
    widgets:
      - type: text
        text: JACKPOT
        style: dmd_xl
        anchor_y: top
        anchor_x: center
        y: top
        x: center
        color: ff00ff
      - type: text
        text: 1,000,000
        style: dmd_xl
        anchor_y: bottom
        anchor_x: center
        y: bottom
        x: center
        color: ffffff

widgets:
  vespa_mb_timer_time_remaining:
    - type: text
      text: (ticks)
      color: blue
      font_name: atrox
      font_size: 130
      anchor_x: right
      anchor_y: top
      x: right-300
      y: top-300
      z: 5
      
