#config_version=5
high_score:
  _overwrite: True
  categories: !!omap
  - score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
  defaults:
    score:
      - BRI: 10000000
      - JK: 8000000
      - GHK: 9500000
      - QC: 7500000
      - JAM: 100000

slides:
  high_score_award_display:
  - type: text
    text: (player_name)
    color: ffffff
    style: dmd_big
    anchor_y: middle
    anchor_x: middle
    x: middle
    y: middle
  - type: text
    text: (award)
    color: ffffff
    style: dmd_med
    anchor_y: top
    anchor_x: middle
    y: top-1
    x: middle
  - type: text
    text: (value)
    color: ffffff
    number_grouping: true
    style: dmd_med
    anchor_y: bottom
    anchor_x: middle
    y: bottom+1
    x: middle
