#config_version=5
mode:
  start_events: ball_starting start_orbit_base_mode_request
  stop_events: stop_orbit_base_mode_request
  priority: 300

sequence_shots:
  left_orbit_base_sequence:
    switch_sequence:
      - s_left_spinner
      - s_right_orbit
    sequence_timeout: 2s
  right_orbit_base_sequence:
    switch_sequence: s_right_orbit
    delay_switch_list:
      s_left_spinner: 1.0s

shots:
  left_orbit_base_shot:
    profile: orbit_base_profile
    hit_events: left_orbit_base_sequence_hit
    show_tokens:
        led: rgb_left_orbit_arrow_1
  right_orbit_base_shot:
    hit_events: right_orbit_base_sequence_hit
    profile: orbit_base_profile
    show_tokens:
        led: rgb_right_orbit_arrow_1

shot_profiles:
  orbit_base_profile:
    states:
      - name: start
        show: orbit_base_blinking
        sync_ms: 500
        loops: -1
      - name: lightspeed
        show: orbit_base_lightspeed
        sync_ms: 500
        loops: -1
      - name: ridiculousspeed
        show: orbit_base_ridiculousspeed
        sync_ms: 500
        loops: -1
      - name: ludicrousspeed
        show: orbit_base_ludicrousspeed
        sync_ms: 500
        loops: -1
      - name: plaidspeed
        show: orbit_base_plaidspeed
        sync_ms: 500
        loops: -1

shot_groups:
    orbit_base_both_shots:
        shots: left_orbit_base_shot, right_orbit_base_shot
        rotate_left_events: s_sling_right_active
        rotate_right_events: s_sling_left_active
        enable_events: ball_started
        disable_events: ball_ending
