#config_version=5
mode:
  start_events: ball_starting
  priority: 800

sound_player:
  pop_bumpers_hit:
    pop_bumper_hit_sound_pool:
      action: play

show_player:
  pop_bumpers_hit:
    pops_flash:
      loops: 0
      speed: 1
  s_pop_1_active:
    pop_1_hit_splash:
      loops: 0
      speed: 1
  s_pop_2_active:
    pop_2_hit_splash:
      loops: 0
      speed: 1
  s_pop_3_active:
    pop_3_hit_splash:
      loops: 0
      speed: 1

event_player:
  s_pop_1_active: pop_bumpers_hit
  s_pop_2_active: pop_bumpers_hit
  s_pop_3_active: pop_bumpers_hit

variable_player:
  s_pop_1_active:
    score: 10000 * current_player.game_scoring_multiplier
    pophits: 1
  s_pop_2_active:
    score: 10000 * current_player.game_scoring_multiplier
    pophits: 1
  s_pop_3_active:
    score: 10000 * current_player.game_scoring_multiplier
    pophits: 1

sound_pools:
  pop_bumper_hit_sound_pool:
    load: preload
    type: random
    track: sfx
    sounds:
      - pop_bumper_1
      - pop_bumper_2
      - pop_bumper_3
      - pop_bumper_4
      - pop_bumper_5
