#config_version=5

mode_settings:
  display_delay_ms: 1000ms
  keep_multiplier: false
  bonus_entries:
      - event: bonus_pops
        score: 10000
        player_score_entry: pophits
        reset_player_score_entry: True
        skip_if_zero: true
      - event: bonus_spins
        score: 2000
        player_score_entry: spinnerhits
        reset_player_score_entry: True
        skip_if_zero: true

slide_player:
  bonus_start:
    bonus_award_start:
      target: dmd
  bonus_pops:
    bonus_award_pops:
      target: dmd
  bonus_spins:
    bonus_award_spins:
      target: dmd
  bonus_subtotal:
    bonus_award_subtotal:
      target: dmd
  bonus_multiplier:
    bonus_award_multiplier:
      target: dmd
  bonus_total:
    bonus_award_total:
      target: dmd

sound_player:
  bonus_start:
    tonal_stab_1:
      action: play
  bonus_pops:
    pinball_pop_bumper:
      action: play
  bonus_spins:
    spinner_beep_1:
      action: play
  bonus_subtotal:
    tonal_stab_1:
      action: play
  bonus_multiplier:
    tonal_stab_1:
      action: play
  bonus_total:
    elevator_ding:
      action: play
  

slides:
  bonus_award_start:
    widgets:
      - type: text
        text: BONUS
        style: dmd_big
        anchor_y: center
        anchor_x: center
        y: center
        x: center
  bonus_award_pops:
    widgets:
      - type: text
        text: POP HITS
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top
        x: center
      - type: text
        text: (hits) x 10,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 5
        x: center
  bonus_award_spins:
    widgets:
      - type: text
        text: SPINNER HITS
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top
        x: center
      - type: text
        text: (hits) x 2,000
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 5
        x: center
  bonus_award_subtotal:
    widgets:
      - type: text
        text: BONUS SUBTOTAL
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top
        x: center
      - type: text
        text: (score)
        number_grouping: True
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 5
        x: center
  bonus_award_multiplier:
    widgets:
      - type: text
        text: BONUS MULTIPLIER
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top
        x: center
      - type: text
        text: (multiplier)X
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 5
        x: center
  bonus_award_total:
    widgets:
      - type: text
        text: BONUS TOTAL
        style: dmd_big
        anchor_y: top
        anchor_x: center
        y: top
        x: center
      - type: text
        text: (score)
        number_grouping: True
        style: dmd_big
        anchor_y: bottom
        anchor_x: center
        y: 5
        x: center
