#config_version=5

hardware:
  platform: fast
  driverboards: fast
  rgb_dmd: smartmatrix

smartmatrix:
  dmd:
    port: com7
    baud: 2500000
    old_cookie: true

rgb_dmds:
  dmd:
    hardware_brightness: 0.3
    fps: 20
    source_display: dmd

fast:
  ports: com4, com5
  
config:
- machine-config.yaml

displays:
  lcd:
    width: 1360
    height: 768
  dmd:
    width: 128
    height: 32
    default: True

window:
  width: 1360 
  height: 768
  #fullscreen: true
  borderless: true
  title: Spaceballs
  resizable: false
  exit_on_escape: true
  source_display: lcd

