#config_version=5

hardware:
  platform: fast
  driverboards: fast
  rgb_dmd: smartmatrix

rgb_dmds:
  smartmatrix_1:
     hardware_brightness: 1.0
     fps: 20
     platform: smartmatrix

fast:
#config_number_format: int
#debug: true
  
config:
- machine-config.yaml

displays:
  lcd:
    width: 1360
    height: 768
  dmd:
    width: 128
    height: 32
    default: true

window:
  width: 1360 
  height: 768
  #fullscreen: true
  borderless: true
  title: Spaceballs
  resizable: false
  exit_on_escape: true
  source_display: lcd

