#config_version=5
assets:
  sounds:
    default:
      load: preload
    voice:
      load: preload
      track: voice
    sfx:
      load: preload
      track: sfx
    music:
      load: preload
      track: music

sound_pools:
  multiball_callout_sound_pool:
    load: preload
    type: random
    track: voice
    sounds:
      - multiball_1
      - multiball_2
  jackpot_callout_sound_pool:
    load: preload
    type: random
    track: voice
    sounds:
      - jackpot_1
      - jackpot_2
  ridiculous_jackpot_callout_sound_pool:
    load: preload
    type: random
    track: voice
    sounds:
      - ridiculous_jackpot_1
      - ridiculous_jackpot_2
      - ridiculous_jackpot_3
      - ridiculous_jackpot_4

sounds:
  service_switch_hit:
    target: sfx
  service_enter:
    target: sfx
  service_exit:
    target: sfx
  service_minus:
    target: sfx
  service_plus:
    target: sfx  
  light_saber_swing_1:
    volume: 0.20
  light_saber_swing_2:
    volume: 0.20
  light_saber_swing_3:
    volume: 0.20
  light_saber_swing_4:
    volume: 0.20
  elevator_ding:
    volume: 0.30
  spaceballs_song:
    target: music
    volume: 0.70
  hello_my_baby:
    target: sfx
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.15
      release_point: 0.5 sec
      release: 2.0 sec
  skillshot_2:
    target: voice
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 0.5 sec
      release: 1.0 sec
  game_over_3:
    target: voice
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 1.0 sec
      release: 1.0 sec
  lightspeed_2:
    target: voice
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 0.5 sec
      release: 1.0 sec
  ridiculous_speed_1:
    target: voice
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 0.5 sec
      release: 1.0 sec
  ludicrous_speed_1:
    target: voice
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 0.5 sec
      release: 1.0 sec
  ball_saved_2:
    target: voice
    ducking:
      target: music
      delay: 0
      attack: 0.3 sec
      attenuation: 0.45
      release_point: 0.5 sec
      release: 1.0 sec
