#config_version=5
mode:
    start_events: ball_starting
    priority: 1500

variable_player:
  skillshot_timing_bonusawardmax:
    bonus_multiplier: 4
  skillshot_timing_bonusaward2:
    score: 250000
  skillshot_timing_bonusaward1:
    score: 100000

coil_player:
  mode_skillshot_timing_started:
    c_launch_light:
      action: enable
  sw_launch:
    c_launch_light:
      action: disable

sound_player:
  skillshot_timing_bonusawardmax:
    skillshot_2:
      action: play
  skillshot_timing_bonusaward2:
    launchboom_1:
      action: play
  skillshot_timing_bonusaward1:
    launchboom_1:
      action: play
  

show_player:
  mode_skillshot_timing_started:
    skillshot_timing_crawl:
      loops: -1
      speed: 6
  skillshot_timing_bonusawardmax:
    skillshot_timing_crawl:
      action: stop
    skillshot_maxlevel_flash:
      loops: 0
      speed: 8
  skillshot_timing_bonusaward2:
    skillshot_timing_crawl:
      action: stop
    skillshot_award_flash:
      loops: 1
      speed: 8
      show_tokens:
        award_led: rgb_shooter_arrow_3
        award_color: ffff00
  skillshot_timing_bonusaward1:
    skillshot_timing_crawl:
      action: stop
    skillshot_award_flash:
      loops: 1
      speed: 8
      show_tokens:
        award_led: rgb_shooter_arrow_2
        award_color: ffff00
  skillshot_timing_bonusawardfail:
    skillshot_timing_crawl:
      action: stop
    skillshot_award_flash:
      loops: 1
      speed: 8
      show_tokens:
        award_led: rgb_shooter_arrow_1
        award_color: ff0000

slide_player:
  mode_skillshot_timing_started:
    skillshot_instructions_slide:
      target: lcd
  skillshot_timing_bonusawardmax:
    skillshot_bonus_award_multiplier:
      target: dmd
      expire: 1
  skillshot_timing_bonusaward2:
    skillshot_bonus_award_secondlevel:
      target: dmd
      expire: 1
  skillshot_timing_bonusaward1:
    skillshot_bonus_award_firstlevel:
      target: dmd
      expire: 1
  skillshot_timing_bonusawardfail:
    skillshot_bonus_award_failure:
      target: dmd
      expire: 1
  skillshot_award_step:
    skillshot_instructions_slide:
      target: lcd
      action: remove

event_player:
  sw_launch{device.counters.skillshot_level_counter.value==4 and current_player.skillshot_award_counter_count < 1}: skillshot_timing_bonusawardmax, skillshot_award_step
  sw_launch{device.counters.skillshot_level_counter.value==3 and current_player.skillshot_award_counter_count < 1}: skillshot_timing_bonusawardmax, skillshot_award_step
  sw_launch{device.counters.skillshot_level_counter.value==2 and current_player.skillshot_award_counter_count < 1}: skillshot_timing_bonusaward2, skillshot_award_step
  sw_launch{device.counters.skillshot_level_counter.value==1 and current_player.skillshot_award_counter_count < 1}: skillshot_timing_bonusaward1, skillshot_award_step
  sw_launch{device.counters.skillshot_level_counter.value==0 and current_player.skillshot_award_counter_count < 1}: skillshot_timing_bonusawardfail, skillshot_award_step

counters:
  skillshot_level_counter:
    count_events: skillshot_timing_step
    count_complete_value: 4
    disable_on_complete: false
    enable_events: mode_skillshot_timing_started
    disable_events: mode_skillshot_timing_stopped sw_launch
    reset_events: mode_skillshot_timing_started
  skillshot_award_counter:
    count_events: skillshot_award_step
    enable_events: mode_skillshot_timing_started
    reset_events: mode_skillshot_timing_started

slides:
  skillshot_instructions_slide:
    widgets:
      - type: image
        image: skillshot_instructions
        anchor_y: bottom
        anchor_x: left
        y: 0
        x: 0  
  skillshot_bonus_award_multiplier:
    widgets:
      - type: text
        text: SKILL SHOT MAXED
        style: dmd_big
        anchor_y: top
        anchor_x: middle
        y: top
        x: center
      - type: text
        text: +4X BONUS
        style: dmd_big
        anchor_y: bottom
        anchor_x: middle
        y: bottom
        x: center
  skillshot_bonus_award_secondlevel:
    widgets:
      - type: text
        text: SKILL SHOT LEVEL 2
        style: dmd_big
        anchor_y: top
      - type: text
        text: 250,000
        style: dmd_big
        anchor_y: bottom
  skillshot_bonus_award_firstlevel:
    widgets:
      - type: text
        text: SKILL SHOT LEVEL 1
        style: dmd_big
        anchor_y: top
      - type: text
        text: 100,000
        style: dmd_big
        anchor_y: bottom
  skillshot_bonus_award_failure:
    widgets:
      - type: text
        text: SKILL SHOT MISSED
        style: dmd_big
        anchor_y: top
      - type: text
        text: ASSHOLE
        style: dmd_big
        anchor_y: bottom
