#config_version=5

mode:
  start_events: ball_starting
  priority: 100

sound_player:
  mode_music_manager_started:
    spaceballs_song:
      action: play
      priority: 100
      fade_in: 1s
  mode_bonus_started:
    spaceballs_song:
      action: stop
      fade_out: 2s
  start_base_music_request:
    spaceballs_song:
      action: play
      priority: 100
  resume_base_music_request:
    spaceballs_song:
      action: play
      priority: 100
      start_at: 7s
  stop_base_music_request:
    spaceballs_song:
      action: stop
  start_airlock_multiball_music_request:
    spaceballs_hot_together:
      action: play
      priority: 150
  stop_airlock_multiball_music_request:
    spaceballs_hot_together:
      action: stop
  start_barf_multiball_music_request:
    spaceballs_raise_your_hands:
      action: play
      priority: 151
  stop_barf_multiball_music_request:
    spaceballs_raise_your_hands:
      action: stop
  start_warp_ramp_multiball_music_request:
    spaceballs_good_enough:
      action: play
      priority: 152
  stop_warp_ramp_multiball_music_request:
    spaceballs_good_enough:
      action: stop
  start_sbone_multiball_music_request:
    spaceballs_heartstrings:
      action: play
      priority: 153
  stop_sbone_multiball_music_request:
    spaceballs_heartstrings:
      action: stop
