#config_version=5

mode:
  start_events: start_airlock_qualifier_mode_request
  stop_events: stop_airlock_qualifier_mode_request
  priority: 200

event_player:
  airlock_qualifying_shots_complete: airlock_qualifier_complete|50ms

shots:
  airlock_qualifying_shot_one:
    switch: s_drop_1
    profile: airlock_target_one_profile
    reset_events: airlock_qualifying_shots_complete
  airlock_qualifying_shot_two:
    switch: s_drop_2
    profile: airlock_target_two_profile
    reset_events: airlock_qualifying_shots_complete
  airlock_qualifying_shot_three:
    switch: s_drop_3
    profile: airlock_target_three_profile
    reset_events: airlock_qualifying_shots_complete
  airlock_qualifying_shot_four:
    switch: s_drop_4
    profile: airlock_target_four_profile
    reset_events: airlock_qualifying_shots_complete
  airlock_qualifying_shot_five:
    switch: s_drop_5
    profile: airlock_target_five_profile
    reset_events: airlock_qualifying_shots_complete

logic_blocks:
  accruals:
    airlock_qualifying_shots:
      events:
        - airlock_qualifying_shot_one_ready_hit
        - airlock_qualifying_shot_two_ready_hit
        - airlock_qualifying_shot_three_ready_hit
        - airlock_qualifying_shot_four_ready_hit
        - airlock_qualifying_shot_five_ready_hit
      events_when_complete: airlock_qualifying_shots_complete

shot_profiles:
  airlock_target_one_profile:
    states:
      - name: ready
        show: airlock_one_ready
        sync_ms: 500
        loops: -1
      - name: lit
        show: airlock_one_lit
  airlock_target_two_profile:
    states:
      - name: ready
        show: airlock_two_ready
        sync_ms: 500
        loops: -1
      - name: lit
        show: airlock_two_lit
  airlock_target_three_profile:
    states:
      - name: ready
        show: airlock_three_ready
        sync_ms: 500
        loops: -1
      - name: lit
        show: airlock_three_lit
  airlock_target_four_profile:
    states:
      - name: ready
        show: airlock_four_ready
        sync_ms: 500
        loops: -1
      - name: lit
        show: airlock_four_lit
  airlock_target_five_profile:
    states:
      - name: ready
        show: airlock_five_ready
        sync_ms: 500
        loops: -1
      - name: lit
        show: airlock_five_lit

scoring:
  airlock_qualifying_shot_one_ready_hit:
    score: 50000 * current_player.game_scoring_multiplier
  airlock_qualifying_shot_two_ready_hit:
    score: 50000 * current_player.game_scoring_multiplier
  airlock_qualifying_shot_three_ready_hit:
    score: 50000 * current_player.game_scoring_multiplier
  airlock_qualifying_shot_four_ready_hit:
    score: 50000 * current_player.game_scoring_multiplier
  airlock_qualifying_shot_five_ready_hit:
    score: 50000 * current_player.game_scoring_multiplier
  airlock_qualifying_shots_complete:
    score: 1000000 * current_player.game_scoring_multiplier
