#config_version=5
mode:
  start_events: ball_starting
  priority: 800

event_player:
  #start the qualifier when the mode manager first starts up
  mode_sbone_modemanager_started: start_sbone_qualifier_one_mode_request
  #start/stop the qualifier when airlock multiball happens
  start_airlock_multiball_mode_request: stop_sbone_qualifier_one_mode_request
  stop_airlock_multiball_mode_request: start_sbone_qualifier_one_mode_request
  #start/stop the qualifier when warp ramp multiball happens
  start_warp_ramp_multiball_mode_request: stop_sbone_qualifier_one_mode_request
  stop_warp_ramp_multiball_mode_request: start_sbone_qualifier_one_mode_request
  #start/stop the qualifier when barf multiball happens
  start_barf_multiball_mode_request: stop_sbone_qualifier_one_mode_request
  stop_barf_multiball_mode_request: start_sbone_qualifier_one_mode_request
  #if the qualifier is complete, start up multiball
  sbone_qualifier_one_complete: stop_sbone_qualifier_one_mode_request, start_sbone_vespa_multiball_mode_request, start_sbone_autoeject_request, stop_base_music_request, start_sbone_multiball_music_request|10ms
  #if multiball is complete, start up the qualifier and award a gem
  sbone_vespa_multiball_complete: stop_sbone_vespa_multiball_mode_request, start_sbone_qualifier_one_mode_request, award_next_schwartz_gem, stop_sbone_autoeject_request, reset_drop_target_bank_request, resume_base_music_request|10ms, stop_sbone_multiball_music_request