#config_version=5
mode:
  start_events: start_warp_ramp_qualifier_mode_request
  stop_events: stop_warp_ramp_qualifier_mode_request
  priority: 200

shots:
  warp_ramp_qualifier_shot:
    hit_events: warp_ramp_full_hit
    profile: warp_ramp_qualifier_shot_profile
    reset_events: warp_ramp_qualifier_complete

sequence_shots:
  warp_ramp_full:
    switch_sequence: s_ramp_entry, s_ramp_exit
    sequence_timeout: 3s

shot_profiles:
  warp_ramp_qualifier_shot_profile:
    states:
      - name: nospeed
        show: warp_ramp_lightspeed_pending
        loops: -1
      - name: lightspeed
        show: warp_ramp_ridiculousspeed_pending
        loops: -1
      - name: ridiculousspeed
        show: warp_ramp_ludicrousspeed_pending
        loops: -1
      - name: ludicrousspeed
        show: warp_ramp_plaidspeed_pending
        loops: -1
      - name: plaidspeed
        show: warp_ramp_plaidspeed_complete
        loops: -1

event_player:
  warp_ramp_qualifier_shot_nospeed_hit: warp_ramp_level_lightspeed_achieved
  warp_ramp_qualifier_shot_lightspeed_hit: warp_ramp_level_ridiculousspeed_achieved
  warp_ramp_qualifier_shot_ridiculousspeed_hit: warp_ramp_level_ludicrousspeed_achieved
  warp_ramp_qualifier_shot_ludicrousspeed_hit: warp_ramp_level_plaidspeed_achieved
  warp_ramp_level_plaidspeed_achieved: warp_ramp_qualifier_complete|50ms
  
variable_player:
  warp_ramp_level_lightspeed_achieved:
    score: 100000 * current_player.game_scoring_multiplier
  warp_ramp_level_ridiculousspeed_achieved:
    score: 200000 * current_player.game_scoring_multiplier
  warp_ramp_level_ludicrousspeed_achieved:
    score: 300000 * current_player.game_scoring_multiplier
  warp_ramp_level_plaidspeed_achieved:
    score: 1000000 * current_player.game_scoring_multiplier
