#config_version=5
mode:
  start_events: start_sbone_qualifier_one_mode_request
  stop_events: stop_sbone_qualifier_one_mode_request
  priority: 200

event_player:
  mode_sbone_qualifier_one_started: sbone_lock_servo_closed
  player_sbone_mb_lock_locked_balls{value==1}: sbone_ball_one_locked
  player_sbone_mb_lock_locked_balls{value==2}: sbone_ball_two_locked
  player_sbone_mb_lock_locked_balls{value==3}: sbone_ball_three_locked
  
queue_event_player:
  sbone_ball_three_locked:
    queue_event: initiate_sbone_vespa_qualifier_complete_fanfare
    events_when_finished: sbone_qualifier_one_complete
  
show_player:
  mode_sbone_qualifier_one_started:
    sbone_qualifier_locks_ready:
      loops: -1
      speed: 1

multiball_locks:
  sbone_mb_lock:
    balls_to_lock: 3
    lock_devices: bd_sbone
    reset_count_for_current_player_events: sbone_qualifier_one_complete